import type { Metadata } from 'next'
import { twMerge } from 'tailwind-merge'

import { Sidebar } from './components/Sidebar'

import './global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className="antialiased">
      <body>
        <div
          className={twMerge(
            'min-h-screen lg:grid lg:grid-cols-app',
            'dark:bg-zinc-900',
          )}
        >
          <Sidebar />

          <main className="max-w-[100vw] px-4 pb-12 pt-24 lg:col-start-2 lg:px-8 lg:pt-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
